export const TYPE_ORDER: Record<string, number> = {
  // Central government
  'Ministerial department': 100,
  'Non-ministerial department': 95,
  'Executive office': 90,
  'Executive agency': 85,
  'Executive agency in the Scottish government': 82,
  'Executive non-departmental public body': 80,
  'Advisory non-departmental public body': 75,
  'Government agency': 72,
  'Government organization': 70,
  'Tribunal': 65,
  'Public corporation': 60,
  'Independent monitoring body': 55,
  'Bicameral legislature': 52,
  'Elected legislative house': 50,
  'Special health authority': 45,
  'NHS foundation trust': 42,
  'Health system': 40,
  'Civil service': 35,
  'Sub organisation': 30,
  'Nonprofit organization': 25,
  'Archives': 22,
  'Organization': 20,
  // Unknown types (Ad-hoc advisory group, Court, Devolved government, Other) → fallback 13
  // Local government — higher = larger area covered
  'Strategic regional authority': 12,
  'Combined authority': 11,
  'County council': 10,
  'Metropolitan district': 9,
  'London borough': 8,
  'Unitary authority': 7,
  'Scottish unitary authority council': 6,
  'Non-metropolitan district': 5,
  'National park authority': 4,
  'Scottish council': 3,
  'Welsh council': 2,
  'Northern Ireland district': 1,
  'Local authority': 0,
  'Special district': -1,
  'Fire service in the United Kingdom': -2,
};
